<html>
<head>
<title>TestNG:  My test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>My test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>2/6/0</td>
</tr><tr>
<td>Started on:</td><td>Wed Apr 03 13:15:33 IST 2019</td>
</tr>
<tr><td>Total time:</td><td>86 seconds (86504 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testcases.EnterCItyName_Testcases.Login_process()'><b>Login_process</b><br>Test class: testcases.EnterCItyName_Testcases<br>Parameters: aberdeen</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 1 expected [4] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 2 expected [7] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [5],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006]
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1725305496", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1725305496'><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 1 expected [4] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 2 expected [7] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [5],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>12</td>
<td>testcases.EnterCItyName_Testcases@cb5822</td></tr>
<tr>
<td title='testcases.EnterCItyName_Testcases.Login_process()'><b>Login_process</b><br>Test class: testcases.EnterCItyName_Testcases<br>Parameters: dundee</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [7] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [7],
	Verifying the maximum pressure for the day 4 expected [1019] but found [1014]
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace610379308", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace610379308'><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [7] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [7],
	Verifying the maximum pressure for the day 4 expected [1019] but found [1014]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>10</td>
<td>testcases.EnterCItyName_Testcases@cb5822</td></tr>
<tr>
<td title='testcases.EnterCItyName_Testcases.Login_process()'><b>Login_process</b><br>Test class: testcases.EnterCItyName_Testcases<br>Parameters: edinburgh</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1074466829", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1074466829'><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>8</td>
<td>testcases.EnterCItyName_Testcases@cb5822</td></tr>
<tr>
<td title='testcases.EnterCItyName_Testcases.Login_process()'><b>Login_process</b><br>Test class: testcases.EnterCItyName_Testcases<br>Parameters: glasgow</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [6] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [10] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace417428478", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace417428478'><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [6] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [10] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>10</td>
<td>testcases.EnterCItyName_Testcases@cb5822</td></tr>
<tr>
<td title='testcases.EnterCItyName_Testcases.Login_process()'><b>Login_process</b><br>Test class: testcases.EnterCItyName_Testcases<br>Parameters: perth</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [4] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [8] but found [5],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [9] but found [8]
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace341169543", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace341169543'><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [4] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [8] but found [5],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [9] but found [8]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>12</td>
<td>testcases.EnterCItyName_Testcases@cb5822</td></tr>
<tr>
<td title='testcases.EnterCItyName_Testcases.Login_process()'><b>Login_process</b><br>Test class: testcases.EnterCItyName_Testcases<br>Parameters: stirling</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [3] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [4] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [6] but found [4],
	Verifying the maximum pressure for the day 4 expected [987] but found [982],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [7] but found [6]
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace687464759", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace687464759'><pre>java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [3] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [4] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [6] but found [4],
	Verifying the maximum pressure for the day 4 expected [987] but found [982],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [7] but found [6]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>9</td>
<td>testcases.EnterCItyName_Testcases@cb5822</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testcases.Browser_URL_Launch.Browser_Launch()'><b>Browser_Launch</b><br>Test class: testcases.Browser_URL_Launch<br>Parameters: chrome</td>
<td></td>
<td>8</td>
<td>testcases.Browser_URL_Launch@cc285f4</td></tr>
<tr>
<td title='testcases.Browser_URL_Launch.urllaunch()'><b>urllaunch</b><br>Test class: testcases.Browser_URL_Launch<br>Parameters: http://localhost:3000/</td>
<td></td>
<td>12</td>
<td>testcases.Browser_URL_Launch@cc285f4</td></tr>
</table><p>
</body>
</html>